# fly.toml app configuration file generated for screenshot-scraper on 2024-10-09T14:10:17-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'screenshot-scraper'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
